[package]
name = "swf-emitter"
version = "0.7.0"
authors = ["Charles Samborski <demurgos@demurgos.net>"]
description = "SWF emitter"
documentation = "https://github.com/open-flash/swf-emitter"
homepage = "https://github.com/open-flash/swf-emitter"
repository = "https://github.com/open-flash/swf-emitter"
readme = "./README.md"
keywords = ["emitter", "swf", "flash"]
license = "AGPL-3.0-or-later"
edition = "2018"

[lib]
name = "swf_emitter"
path = "src/lib.rs"

[[bin]]
name = "swf-emitter"
path = "src/main.rs"

[dependencies]
byteorder = "^1.3.1"
half = "^1.3.0"
serde_json = "^1.0.39"
swf-tree = "^0.7.0"
swf-fixed = "^0.1.4"

[dev-dependencies]
swf-parser = "^0.7.0"
test-generator = "^0.2.2"

# [replace]
# "swf-tree:0.4.1" = { path = '../../swf-tree/rs' }

# When testing larger files, increasing `opt-level` provides a significant speed-up.
# [profile.test]
# opt-level = 2
